from typing import Protocol
from src.shop.domain.entities import ShopItem


class ShopRepository(Protocol):
    async def get_by_id(self, item_id: int) -> ShopItem | None: ...
    async def list_active(self) -> list[ShopItem]: ...
    async def add(self, item: ShopItem) -> ShopItem: ...
    async def save(self, item: ShopItem) -> ShopItem: ...
    async def delete(self, item_id: int) -> None: ...
