from typing import Protocol
from src.battles.domain.entities import Battle


class BattleRepository(Protocol):
    async def get_by_id(self, battle_id: int) -> Battle | None: ...
    async def add(self, battle: Battle) -> Battle: ...
    async def save(self, battle: Battle) -> Battle: ...
    async def delete(self, battle_id: int) -> None: ...
    async def get_active_by_player(self, player_id: int) -> Battle | None: ...
