from typing import Protocol
from src.clans.domain.entities import Clan


class ClanRepository(Protocol):
    async def get_by_id(self, clan_id: int) -> Clan | None: ...
    async def find_by_player(self, player_id: int) -> Clan | None: ...
    async def list_all(self) -> list[Clan]: ...
    async def add(self, clan: Clan) -> Clan: ...
    async def save(self, clan: Clan) -> Clan: ...
    async def delete(self, clan_id: int) -> None: ...
