from __future__ import annotations
from typing import Protocol
from yuqa.shop.domain.entities import ShopItem


class ShopRepository(Protocol):
    async def get_by_id(self, item_id: int) -> ShopItem | None: ...
    async def list_active(self) -> list[ShopItem]: ...
    async def add(self, item: ShopItem) -> None: ...
    async def save(self, item: ShopItem) -> None: ...
