from typing import Protocol
from yuqa.cards.domain.entities import CardTemplate, PlayerCard


class CardTemplateRepository(Protocol):
    async def get_by_id(self, template_id: int) -> CardTemplate | None: ...
    async def list_active(self) -> list[CardTemplate]: ...
    async def add(self, template: CardTemplate) -> CardTemplate: ...
    async def save(self, template: CardTemplate) -> CardTemplate: ...
    async def delete(self, template_id: int) -> None: ...


class PlayerCardRepository(Protocol):
    async def get_by_id(self, card_id: int) -> PlayerCard | None: ...
    async def list_by_owner(self, player_id: int) -> list[PlayerCard]: ...
    async def add(self, card: PlayerCard) -> PlayerCard: ...
    async def save(self, card: PlayerCard) -> PlayerCard: ...
    async def delete(self, card_id: int) -> None: ...
