from typing import Protocol
from yuqa.banners.domain.entities import Banner


class BannerRepository(Protocol):
    async def get_by_id(self, banner_id: int) -> Banner | None: ...
    async def list_available(self) -> list[Banner]: ...
    async def add(self, banner: Banner) -> Banner: ...
    async def save(self, banner: Banner) -> Banner: ...
    async def delete(self, banner_id: int) -> None: ...
