from typing import Protocol
from yuqa.players.domain.entities import Player, ProfileBackgroundTemplate


class PlayerRepository(Protocol):
    async def get_by_telegram_id(self, telegram_id: int) -> Player | None: ...
    async def get_by_id(self, telegram_id: int) -> Player | None: ...
    async def get_by_nickname(self, nickname: str) -> Player | None: ...
    async def list_all(self) -> list[Player]: ...
    async def add(self, player: Player) -> Player: ...
    async def save(self, player: Player) -> Player: ...
    async def delete(self, telegram_id: int) -> None: ...


class ProfileBackgroundRepository(Protocol):
    async def get_by_id(
        self, background_id: int
    ) -> ProfileBackgroundTemplate | None: ...
    async def list_all(self) -> list[ProfileBackgroundTemplate]: ...
    async def add(
        self, background: ProfileBackgroundTemplate
    ) -> ProfileBackgroundTemplate: ...
    async def save(
        self, background: ProfileBackgroundTemplate
    ) -> ProfileBackgroundTemplate: ...
    async def delete(self, background_id: int) -> None: ...
