from __future__ import annotations
from typing import Protocol
from yuqa.quests.domain.entities import QuestDefinition, QuestProgress


class QuestRepository(Protocol):
    async def get_definition_by_id(self, quest_id: int) -> QuestDefinition | None: ...
    async def list_active_definitions(self) -> list[QuestDefinition]: ...
    async def get_progress(
        self, player_id: int, quest_id: int
    ) -> QuestProgress | None: ...
    async def save_definition(self, definition: QuestDefinition) -> None: ...
    async def save_progress(self, progress: QuestProgress) -> None: ...
