from __future__ import annotations
from typing import Protocol
from yuqa.battle_pass.domain.entities import BattlePassSeason, BattlePassProgress


class BattlePassRepository(Protocol):
    async def get_season_by_id(self, season_id: int) -> BattlePassSeason | None: ...
    async def list_active_seasons(self) -> list[BattlePassSeason]: ...
    async def get_progress(
        self, player_id: int, season_id: int
    ) -> BattlePassProgress | None: ...
    async def save_season(self, season: BattlePassSeason) -> None: ...
    async def save_progress(self, progress: BattlePassProgress) -> None: ...
