from __future__ import annotations
from typing import Protocol
from yuqa.battles.domain.entities import Battle


class BattleRepository(Protocol):
    async def get_by_id(self, battle_id: int) -> Battle | None: ...
    async def add(self, battle: Battle) -> None: ...
    async def save(self, battle: Battle) -> None: ...
    async def get_active_battle_for_player(self, player_id: int) -> Battle | None: ...
