from __future__ import annotations
from typing import Protocol
from yuqa.clans.domain.entities import Clan


class ClanRepository(Protocol):
    async def get_by_id(self, clan_id: int) -> Clan | None: ...
    async def get_by_owner(self, owner_player_id: int) -> Clan | None: ...
    async def add(self, clan: Clan) -> None: ...
    async def save(self, clan: Clan) -> None: ...
    async def delete(self, clan: Clan) -> None: ...
