
from typing import Protocol

from yuqa.ideas.domain.entities import Idea


class IdeaRepository(Protocol):
    async def get_by_id(self, idea_id: int) -> Idea | None: ...
    async def list_all(self) -> list[Idea]: ...
    async def add(self, idea: Idea) -> None: ...
    async def save(self, idea: Idea) -> None: ...
